### ISSUE TITLE
Frequent disconnects with Tor

### ISSUE THREAD

**Issue by kaminsky9444** [freenode/ircd-seven#169]
Hello,

I usually use Freenode with Tor, and I notice a problem. 
After a few days of connection (maximum 3 days), the IRCD of Freenode disconnects me with the following message :

`warning SSL read error: server closed connection unexpectedly.`

Why can not I go beyond 3 days of connection?.

`Tor version : 0.2.9.16-1.`
`Irssi version : 1.2.0.`
`OpenSSL version : 1.1.0j-1~deb9u1.`

Thanks you !.

**Comment by kaminsky9444** [comment]
I will provide the rawlog in the coming days.

**Comment by bigpresh** [comment]
I wouldn't consider Tor a reliable connection method for long-standing connections; Tor nodes anywhere along the path can come and go.  If you want to stay connected for a long time, Tor is not for you, I'd say.

I'll close this as it won't be an ircd issue, otherwise it would affect non-Tor users too.

**Comment by mquin** [comment]
Setting "LongLivedPorts 6697" in your torrc may help you get a more reliable path through the network.

I've been able to maintain connections for longer than three days from a system with that set, but drops do still happen occasionally and are likely unavoidable given the design of Tor.

**Comment by kaminsky9444** [comment]
@mquin,

After 1 day .. :

https://nsa40.casimages.com/img/2019/06/22/190622071344122554.jpg.
