### ISSUE TITLE
Disable /stats p throttling or at least raise the limit

### ISSUE THREAD

**Issue by Fuchs** [freenode/ircd-seven#8]
Given that #freenode now heavily relies on /stats p and enough bots, scripts and users abuse it: 

I suggest removing the limit of /stats p or at least raise it considerably, as the limit is quite often hit and then unvoiced users have no idea who to contact.

**Comment by AbstractBeliefs** [comment]
Turns out the throttling for stats applies to /stats as a whole (https://github.com/freenode/ircd-seven/blob/cbf070e4720cf6ab4a10bd5f2fc06b7459b26c12/modules/m_stats.c#L197) . Adding per-option timeouts is something that could be done, but it takes >10m to do so I'd rather have buy in from infra before doing so.

**Comment by xnrand** [comment]
This problem appears to be larger than just /stats. Global throttling affects commands like /motd too (not the *same* limit as /stats but it works the same). A solution for globally throttled commands would benefit cases like /motd too.

**Comment by xnrand** [comment]
Idea: Add just one field (time_t -> 8 bytes) to the local user struct, indicating when the last "slow" (rate-limited) command was used. Use that for commands like /stats,/motd,/list,etc. so that there is reasonable rate-limiting without users affecting each other.
